apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-configmap-oci
data:
  test.sh: |
    #!/bin/sh

    #set env
    export ETCDCTL_API=3
    export ETCD_ENDPOINT=

    
    #authentication


    #take a snapshot
    echo "ETCD_ENDPOINT=$ETCD_ENDPOINT"
    ETCDCTL_API=3 etcdctl snapshot save --endpoints=$ETCD_ENDPOINT --cacert=/cert/ca.cert  --cert=/cert/server.crt  --key=/cert/server.key  etcd-backup.db --debug
    ETCDCTL_API=3 etcdctl --write-out=table snapshot status etcd-backup.db


    #backup to the oci storage


    #delete backup file
    #rm -rf etcd-backup.db
    
