apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-configmap-ncp
data:
  test.sh: |
    #!/bin/sh

    #set env
    export ncloud_access_key_id = 
    export ncloud_secret_access_key = 
    export ncloud_api_url = https://ncloud.apigw.ntruss.com
    export ENDPOINT = 


    #install ncp-cli
    wget https://www.ncloud.com/api/support/download/5/65
    unzip 65
    cd cli_linux/
    chmod 755 -R *
    echo "[DEFAULT]" > ~/.ncloud/configure
    echo "ncloud_access_key_id = $ncloud_access_key_id" >> ~/.ncloud/configure
    echo "ncloud_secret_access_key = $ncloud_secret_access_key" >> ~/.ncloud/configure

    
    #authentication


    #take a snapshot
    echo "ENDPOINT=$ENDPOINT"
    etcdctl snapshot save --endpoints=$ENDPOINT etcd-backup.db
    etcdctl --write-out=table snapshot status etcd-backup.db


    #backup to the cloud


    #delete backup file
    #rm -rf etcd-backup.db
    
