apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-backup-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      securityContext: #root 권한
        runAsUser: 0
      containers: 
      - name: etcd-backup 
        image: bitnami/etcd       # etcdctl image 불러오기
        command: ["sh", "/scripts/test.sh"]
        volumeMounts:
        - name: script-volume       
          mountPath: /scripts
        - name: pv-cert
          mountPath: /cert
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: etcd-backup-configmap-oci
      - name : pv-cert
        persistentVolumeClaim:
          claimName: pvc-cert
  backoffLimit: 3
