apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-configmap-aws
data:
  test.sh: |
    #!/bin/sh

    #set env
    export ETCDCTL_API=3
    export ETCD_ENDPOINT=10.0.0.145

    export AWS_ACCESS_KEY_ID="AKIA4DLHR6AAARIOHEU6"
    export AWS_SECRET_ACCESS_KEY="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"
    export AWS_REGION="ap-northeast-2"
    export BUCKET_NAME="jujy-etcd-backup-$AWS_REGION"


    #== aws config ==
    # directory 생성
    mkdir -p ~/.aws

    # configure 파일 생성
    cat > ~/.aws/config << EOF
    [default]
    region = $AWS_REGION
    output = json
    EOF

    # credential file 생성
    cat > ~/.aws/credentials << EOF
    [default]
    aws_access_key_id = $AWS_ACCESS_KEY_ID
    aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
    EOF

    # 권한 부여
    chmod 600 ~/.aws/config ~/.aws/credentials

    #== create s3 ==
    if aws s3 ls "s3://$BUCKET_NAME" --region "$AWS_REGION" 2>&1 | grep -q 'NoSuchBucket'; then
      echo "Creating S3 bucket: $BUCKET_NAME"
      aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION"

      if [ $? -eq 0 ]; then
        echo "S3 bucket '$BUCKET_NAME' created successfully."
      else
        echo "Failed to create S3 bucket '$BUCKET_NAME'. Please check the error message."
      fi

    else
      echo "Bucket already exists: $BUCKET_NAME"
    fi
    #== Apply s3 lifecycle ==
    aws s3api put-bucket-lifecycle-configuration --bucket $BUCKET_NAME --lifecycle-configuration file://aws-lifecycle.json


    #take a snapshot
    echo "ETCD_ENDPOINT=$ETCD_ENDPOINT"
    ETCDCTL_API=3 etcdctl snapshot save --endpoints=$ETCD_ENDPOINT --cacert=/cert/ca.cert  --cert=/cert/server.crt  --key=/cert/server.key  etcd-backup.db --debug
    ETCDCTL_API=3 etcdctl --write-out=table snapshot status etcd-backup.db

    #backup to the oci storage
    timestamp=$(date -u +"%Y-%m-%dT%H:%M")
    aws s3 cp /etcd-backup.db s3://$BUCKET_NAME/
