#Fill in the blanks according to the applicable environment
 
 
 #===================================== etcd certification =====================================
etcd:
  ##Directory that including ca.crt, server.crt, server.key. Please write the path from the master node. Please write an absolute path.
  cert_path: /etc/kubernetes/pki/etcd/  
  #endpoint of etcd with port. This must be Private IP.
  endpoint: 


#===================================== cloudProvider =========================================
#Select the cloudProvider where the etcd backup snapshot will be saved.
#Uncomment what you want. default is oracle cloud.
cloudProvider: oci
#cloudProvider: aws
#cloudProvider: ncp


#Fill in below, if you choosed Oracle Cloud Infrastructure.
oci:
  user_ocid: 
  tenancy_ocid: 
  api_key_content:  #Copy and paste the contents of the oci key file
  bucket_region: 
  namespace: 


#Fill in below, if you choosed Amazon Web Service.
aws:
  access_key_id:
  secret_access_key:
  region:



#Fill in below, if you choosed Naver Cloud Platform.
ncp:
  access_key_id:
  secret_access_key:
  region:

