apiVersion: batch/v1
kind: Job
metadata:
  name: ncp-etcd-backup-job
  namespace: etcd-autobackup
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ''
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext: #root 권한
        runAsUser: 0
      containers:
        - name: etcd-backup
          image: juya/jujy-etcd-custom-aws
          command: ['sh', '/scripts/test.sh']
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: cert-hostpath #etcd certification
              mountPath: /cert
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: etcd-backup-configmap-ncp
        - name: cert-hostpath
          hostPath:
            path: /etc/kubernetes/pki/etcd/
  backoffLimit: 3