apiVersion: batch/v1
kind: Job
metadata:
  name: aws-etcd-backup-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ''
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext: #root 권한
        runAsUser: 0
      containers:
        - name: etcd-backup
          image: juya/jujy-etcd-aws:laste
          command: ['sh', '/scripts/test.sh']
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: cert-hostpath #etcd certification
              mountPath: /cert
            - name: pv-oci-key
              mountPath: /oci-key
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: etcd-backup-configmap-aws
        - name: cert-hostpath
          hostPath:
            path: { { .Values.etcd.cert_path } }
        - name: pv-oci-key
          persistentVolumeClaim:
            claimName: pvc-oci-key
  backoffLimit: 3
