{{- if eq .Values.cloudProvider "aws" }}

apiVersion: batch/v1
kind: Job
metadata:
  name: aws-etcd-backup-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ''
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext: #root 권한
        runAsUser: 0
      containers:
        - name: etcd-backup
          image: na3150/jujy-etcd-custom-aws
          command: ['sh', '/scripts/test.sh']
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: cert-hostpath #etcd certification
              mountPath: /cert
            - name: aws-lifecycle
              mountPath: /etcd-autobackup/storage-shells
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: etcd-backup-configmap-aws
        - name: cert-hostpath
          hostPath:
            path: /etc/kubernetes/pki/etcd/
        - name: aws-lifecycle
          hostPath:
            path: /root/etcd-autobackup/storage-shells/
  backoffLimit: 3

{{- end }}