{{- if eq .Values.cloudProvider "oci" }}

apiVersion: batch/v1
kind: Job
metadata:
  name: oci-etcd-backup-job
  namespace: etcd-autobackup
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector: 
        node-role.kubernetes.io/control-plane: ''
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext: #root 권한
        runAsUser: 0
      containers:
        - name: etcd-backup
          image: na3150/jujy-etcd-custom:latest
          command: ['sh', '/scripts/test.sh']
          volumeMounts:
            - name: script-volume #confimap script 
              mountPath: /scripts
            - name: cert-hostpath #etcd certification
              mountPath: /cert
            - name: key-hostpath #oci-cli key
              mountPath: /oci-key
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: etcd-backup-configmap-oci
        - name: cert-hostpath
          hostPath:
            path: {{ .Values.etcd.cert_path }}
        - name: key-hostpath
          hostPath:
            path: {{ .Values.oci.api_key_path }}
  backoffLimit: 3

{{- end }}